<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Barangay Residents Report</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/adminlte.min.css">
  
  <style>
    .barangay-header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 3px solid rgb(0, 0, 0);
      padding-bottom: 20px;
    }
    .barangay-logo {
      width: 80px;
      height: 80px;
      margin: 0 auto 15px;
      background: #f8f9fa;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 32px;
      color: #007bff;
    }
    .barangay-title {
      font-size: 24px;
      font-weight: bold;
      color:rgb(0, 0, 0);
      margin: 10px 0 5px;
    }
    .barangay-subtitle {
      font-size: 18px;
      font-weight: bold;
      color:rgb(0, 0, 0);
      margin: 5px 0;
    }
    .barangay-address {
      font-size: 14px;
      color:rgb(0, 0, 0);
      margin: 5px 0;
    }
    .report-title {
      font-size: 20px;
      font-weight: bold;
      color:rgb(0, 0, 0);
      margin: 20px 0 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .report-meta {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      margin: 20px 0;
    }
    .filters-applied {
      background: #e3f2fd;
      padding: 15px;
      border-radius: 5px;
      margin: 15px 0;
      border-left: 4px solid #2196f3;
    }
    .residents-table {
      margin-top: 20px;
    }
    .residents-table th {
      background-color: #007bff;
      color: white;
      text-align: center;
      font-weight: bold;
    }
    .residents-table td {
      vertical-align: middle;
    }
    .status-yes {
      color: #28a745;
      font-weight: bold;
    }
    .status-no {
      color: #dc3545;
      font-weight: bold;
    }
    .report-footer {
      margin-top: 40px;
      text-align: center;
      padding-top: 20px;
      border-top: 1px solid #dee2e6;
      color: #6c757d;
      font-size: 12px;
    }
    @media print {
      body { margin: 0; }
      .no-print { display: none !important; }
      .barangay-header { page-break-after: avoid; }
    }
  </style>
</head>
<body>
<div class="wrapper">
  <section class="invoice">
    <!-- Barangay Header -->
    <div class="barangay-header mt-5">
      <div class="barangay-logo mb-2">
        <img src="../server_imgs/logo.jpg" alt="" style="width: 150px; height: 150px; border-radius: 50%;">
      </div>
      <div class="barangay-title mt-5">REPUBLIC OF THE PHILIPPINES</div>
      <div class="barangay-subtitle">Province of Cebu </div>
      <div class="barangay-subtitle">Municipality of Laput-lapu City</div>
      <div class="barangay-title" style="color:rgb(0, 0, 0);">Barangay Buaya</div>
      <div class="barangay-address">
            Barangay Buaya, Lapu-lapu City, Cebu <br>
        Tel. No.:  09753234227 | Email: barangaybuaya23@gmail.com
      </div>
      <div class="report-title">RESIDENTS INFORMATION REPORT</div>
    </div>

    <!-- Report Meta Information -->
    <div class="report-meta">
      <div class="row">
        <div class="col-sm-6">
          <strong>Report Generated:</strong> <span id="reportDate"></span><br>
          <strong>Generated By:</strong> Barangay Administrator<br>
          <strong>Total Records:</strong> <span id="totalRecords">Loading...</span>
        </div>
        <div class="col-sm-6 text-right">
          <strong>Report Type:</strong> Residents Database<br>
          <strong>Status:</strong> <span class="badge badge-success">Active</span><br>
          <strong>Format:</strong> Printable Report
        </div>
      </div>
    </div>

    <!-- Applied Filters -->
    <div class="filters-applied" id="filtersApplied" style="display: none;">
      <h5><i class="fas fa-filter"></i> Resident:</h5>
      <div id="filtersList"></div>
    </div>

    <!-- Residents Table -->
    <div class="row">
      <div class="col-12">
        <div class="table-responsive">
          <table class="table table-bordered table-striped residents-table" id="residentsTable">
            <thead>
              <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 25%;">Full Name</th>
                <th style="width: 10%;">Sex</th>
                <th style="width: 15%;">Civil Status</th>
                <th style="width: 8%;">Age</th>
                <th style="width: 12%;">PWD Status</th>
                <th style="width: 12%;">Senior Status</th>
                <th style="width: 13%;">Voter Status</th>
              </tr>
            </thead>
            <tbody id="residentsData">
              <tr>
                <td colspan="8" class="text-center py-4">
                  <i class="fas fa-spinner fa-spin"></i> Loading residents data...
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Report Footer -->
    <div class="report-footer">
      <div class="row">
        <div class="col-sm-6 text-left">
          <p><strong>Prepared by:</strong></p>
          <br><br>
          <p>_______________________<br>
          <strong>Sec. Ivan B. Timcang</strong><br>
          Barangay Secretary</p>
        </div>
        <div class="col-sm-6 text-right">
          <p><strong>Certified by:</strong></p>
          <br><br>
          <p>_______________________<br>
          <strong>Hon. Jay Mike E. Palang</strong><br>
          Barangay Captain</p>
        </div>
      </div>
      <hr>
      <p style="margin-top: 20px;">
        This report is generated electronically and contains confidential information. 
        Unauthorized distribution is prohibited.<br>
        <small>Generated on: <span id="footerDate"></span> | Page 1 of 1</small>
      </p>
    </div>
  </section>
</div>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
$(document).ready(function() {
    // Set current date and time
    const now = new Date();
    const dateString = now.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: true
    });
    
    $('#reportDate').text(dateString);
    $('#footerDate').text(dateString);
    
    // Get filters from sessionStorage
    const filters = sessionStorage.getItem('reportFilters');
    
    if (filters) {
        displayAppliedFilters(filters);
        loadResidentsForPrint(filters);
    } else {
        loadResidentsForPrint('');
    }
    
    // Auto print after data loads (with delay)
    setTimeout(function() {
        window.print();
    }, 2000);
});

function displayAppliedFilters(filters) {
    const params = new URLSearchParams(filters);
    let hasFilters = false;
    let filtersHtml = '<div class="row">';
    
    for (const [key, value] of params.entries()) {
        if (value && value.trim() !== '') {
            hasFilters = true;
            filtersHtml += `
                <div class="col-sm-4 mb-2">
                    <strong>${formatFilterName(key)}:</strong> 
                    <span class="badge badge-primary">${value}</span>
                </div>
            `;
        }
    }
    
    filtersHtml += '</div>';
    
    if (hasFilters) {
        $('#filtersList').html(filtersHtml);
        $('#filtersApplied').show();
    }
}

function formatFilterName(key) {
    const labels = {
        'res_sex': 'Gender',
        'res_civil_status': 'Civil Status',
        'res_pwd_status': 'PWD Status',
        'res_senior_status': 'Senior Status',
        'res_voter_status': 'Voter Status',
        'age_min': 'Minimum Age',
        'age_max': 'Maximum Age',
        'search': 'Search Term'
    };
    return labels[key] || key.replace('_', ' ').toUpperCase();
}

function loadResidentsForPrint(filters) {
    $.ajax({
        url: "../backend/admin/report.php",
        type: "POST",
        data: filters,
        dataType: "json",
        success: function(response) {
            let html = '';
            let counter = 1;
            
            if (response.success && response.data.length > 0) {
                response.data.forEach(resident => {
                    html += `
                        <tr>
                            <td class="text-center">${counter}</td>
                            <td><strong>${resident.res_first_name} ${resident.res_last_name}</strong></td>
                            <td class="text-center">${resident.res_sex}</td>
                            <td class="text-center">${resident.res_civil_status}</td>
                            <td class="text-center">${calculateAge(resident.res_date_of_birth)}</td>
                            <td class="text-center">
                                <span class="${resident.res_pwd_status ? 'status-yes' : 'status-no'}">
                                    ${resident.res_pwd_status ? 'YES' : 'NO'}
                                </span>
                            </td>
                            <td class="text-center">
                                <span class="${resident.res_senior_status ? 'status-yes' : 'status-no'}">
                                    ${resident.res_senior_status ? 'YES' : 'NO'}
                                </span>
                            </td>
                            <td class="text-center">
                                <span class="${resident.res_voter_status ? 'status-yes' : 'status-no'}">
                                    ${resident.res_voter_status ? 'YES' : 'NO'}
                                </span>
                            </td>
                        </tr>
                    `;
                    counter++;
                });
                
                // Update total records
                $('#totalRecords').text(response.data.length + ' resident(s)');
            } else {
                html = `
                    <tr>
                        <td colspan="8" class="text-center py-4 text-muted">
                            <i class="fas fa-info-circle"></i> No residents found matching your criteria
                        </td>
                    </tr>
                `;
                $('#totalRecords').text('0 residents');
            }
            
            $("#residentsData").html(html);
        },
        error: function(xhr, status, error) {
            console.error("AJAX Error:", error);
            $("#residentsData").html(`
                <tr>
                    <td colspan="8" class="text-center py-4 text-danger">
                        <i class="fas fa-exclamation-triangle"></i> Error loading residents data
                    </td>
                </tr>
            `);
            $('#totalRecords').text('Error');
        }
    });
}

function calculateAge(dob) {
    if (!dob) return 'N/A';
    const birthDate = new Date(dob);
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
        age--;
    }
    return age;
}
</script>

</body>
</html>